# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelplan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='travel_date_from',
            new_name='traveldatefrom',
        ),
    ]
