# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelplan', '0003_auto_20171027_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='tripcreater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripcreated', to='travelplan.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tripjoiners',
            field=models.ManyToManyField(related_name='tripsgoingto', to='travelplan.User'),
        ),
    ]
